### ISSUE TITLE
HHVM error

### ISSUE THREAD

**Issue by gabu69** [Automattic/facebook-instant-articles-wp#65]
Using HHVM instead of PHP, today had to restart my server and suddenly the RSS wasnt being generated, checked my HHVM error.log and this shows up:

`\nFatal error: Uncaught exception 'DOMException' with message 'Hierarchy Request Error' in /var/www/site/public_html/wp-content/plugins/fb-instant-articles/dom-transform-filters/class-instant-articles-dom-transform-filter.php:85\nStack trace:\n#0 /var/www/site/public_html/wp-content/plugins/fb-instant-articles/dom-transform-filters/class-instant-articles-dom-transform-filter.php(85): DOMNode->replaceChild()\n#1 /var/www/site/public_html/wp-content/plugins/fb-instant-articles/dom-transform-filters/class-instant-articles-dom-transform-filter.php(49): Instant_Articles_DOM_Transform_Filter->_transform_element()\n#2 /var/www/site/public_html/wp-content/plugins/fb-instant-articles/dom-transform-filters/class-instant-articles-dom-transform-filter-table.php(23): Instant_Articles_DOM_Transform_Filter->_transform_elements()\n#3 /var/www/site/public_html/wp-content/plugins/fb-instant-articles/class-instant-articles-dom-transform-filter-runner.php(45): Instant_Articles_DOM_Transform_Filter_Table->run()\n#4 /var/www/site/public_html/wp-content/plugins/fb-instant-articles/class-instant-articles-post.php(309): Instant_Articles_DOM_Transform_Filter_Runner::run()\n#5 /var/www/site/public_html/wp-content/plugins/fb-instant-articles/class-instant-articles-post.php(219): Instant_Articles_Post->_get_the_content()\n#6 /var/www/site/public_html/wp-content/plugins/fb-instant-articles/feed-template.php(17): Instant_Articles_Post->get_the_content()\n#7 /var/www/site/public_html/wp-content/plugins/fb-instant-articles/facebook-instant-articles.php(83): include()\n#8 /var/www/site/public_html/wp-includes/plugin.php(525): instant_articles_feed()\n#9 /var/www/site/public_html/wp-includes/functions.php(1236): do_action()\n#10 /var/www/site/public_html/wp-includes/template-loader.php(37): do_feed()\n#11 /var/www/site/public_html/wp-blog-header.php(16): include()\n#12 /var/www/site/public_html/index.php(17): include()\n#13 {main}`

**Comment by gabu69** [comment]
Seems it was a problem with mariadb, some corrupt table, upgraded maria database to the latest, checked, repaired & optimized and everything got fixed
